- name: demo on play level varaibles
  hosts: local
  connection: local
  vars:
    course: "Ansible"
    trainer: "Shiva"
    duration: "150hrs"
  tasks:
  - debug:
      msg: "Hi, I am learning {{ course }}, Trainer is {{ trainer }}, duration is {{ duration }} "