- name: demo on task level varaibles
  hosts: local
  connection: local
  vars:
    course: "Ansible"
    trainer: "Shiva"
    duration: "150hrs"
  tasks:
  - name: print information
    vars:
      course: "DevOps"
    debug:
      msg: "Hi, I am learning {{ course }}, Trainer is {{ trainer }}, duration is {{ duration }} "