- name: demo on inventory
  hosts: local
  connection: local
  tasks:
  - name: print the inventory values
    debug:
      msg: "Hi, I am learning {{ course }}, Trainer is {{ trainer }}, duration is {{ duration }} "