- name: demo on command line
  hosts: frontend
  connection: local
  tasks:
  - name: print the inventory values
    debug:
      msg: "Hi, I am learning {{ course }}, Trainer is {{ trainer }}, duration is {{ duration }} and common key {{ common_key }} and name = {{ name }}"