- name: demo in filters
  hosts: local
  connection: local
  vars:
    topics: Linux, Shell, Ansible, Terraform
    tagMap:
      name: Ansile
      project: roboshop
      environment: Dev
    my_list:
    - key: name
      value: Ansible
    - key: project
      value: roboshop
    - key: environment
      value: Dev
    tagList: [
        {
            "key": "name",
            "value": "Ansile"
        },
        {
            "key": "project",
            "value": "roboshop"
        },
        {
            "key": "environment",
            "value": "Dev"
        }
    ]
    fruits_list:
    - fruit: "apple"
      color: "red"
    - fruit: "pear"
      color: "yellow"
  tasks:
  - name: convert string to list 
    debug:
      msg: "{{ topics | split(',') }}"
  - name: set default value
    debug:
      msg: "Hi, {{ GREETING | default('Good Morning') }}"
  - name: convert map to list
    debug:
      msg: "{{ tagMap | dict2items }}"
  
  - name: convert list to map
    debug:
      msg: "{{ my_list | items2dict }}"
  - name: convert list to map
    debug:
      msg: "{{ tagList | items2dict }}"
      
  - name: convert list to map
    debug:
      msg: "{{ fruits_list | items2dict(key_name='fruit', value_name='color') }}"