- name: demo on error handling
  hosts: local
  connection: local

  tasks:
  - name: run command
    # command: cat /etc/passwd | grep root
    shell: cat /etc/passwd | grep root
    register: users_output
  - name: print output
    debug:
      msg: "{{ users_output }}"  
