[frontend]
172.31.30.235 ;course="Ansible for node 1" trainer="ravikuar"
172.31.18.137 ;course="Ansible for node 2"

[local]
localhost

; [catalogue]
; 172.31.28.182

; [user]
; 172.31.28.183

; [cart]
; 172.31.28.184

; [roboshop::children]
; fronend
; catalogue
; user
; cart

; [local:vars]
; course="Ansible"
; trainer="Shiva"
; duration="150hrs"

; [frontend:vars]
; course="DevOps"
; trainer="Shivakumar"
; duration="150hrs"